src/Century.WebApp/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Century.WebApp.Models;
using Century.Business.Interfaces;
using AutoMapper;
using Century.Business.Models;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Authorization;

namespace Century.WebApp.Controllers
{
    public class ProductsController : BaseController
    {
        private readonly IProductRepository _productRepository;
        private readonly ISupplierRepository _supplierRepository;
        private readonly IMapper _mapper;

        public ProductsController(IProductRepository productRepository,
            ISupplierRepository supplierRepository, IMapper mapper)
        {
            _productRepository = productRepository;
            _supplierRepository = supplierRepository;
            _mapper = mapper;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(_mapper.Map<IEnumerable<ProductViewModel>>(await _productRepository.GetProductsAndSuppliers()));
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(Guid id)
        {
            var productViewModel = await GetProduct(id);

            if (productViewModel == null)
            {
                return NotFound();
            }

            return View(productViewModel);
        }

        public async Task<IActionResult> Create()
        {
            var productViewModel = await FillSupplier(new ProductViewModel());
            return View(productViewModel);
        }

        // POST: Products/Create        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductViewModel productViewModel)
        {
            productViewModel = await FillSupplier(productViewModel);

            if (!ModelState.IsValid)
            {
                return View(productViewModel);
            }

            //Upload de imagem
            var imgImageName = Guid.NewGuid() + "_"; //gerando um guid vc impede 2 confusão de duas imagens com mesmo nome
            if (!await UploadFile(productViewModel.ImageUpload, imgImageName))
            {
                return View(productViewModel);
            }

            productViewModel.ImagePath = imgImageName + productViewModel.ImageUpload.FileName;

            await _productRepository.Adicionar(_mapper.Map<Product>(productViewModel));

            return RedirectToAction("Index");
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(Guid id)
        {
            var productViewModel = await GetProduct(id);

            if (productViewModel == null)
            {
                return NotFound();
            }
            return View(productViewModel);
        }

        // POST: Products/Edit/5        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, ProductViewModel productViewModel)
        {
            if (id != productViewModel.Id)
            {
                return NotFound();
            }

            var productatualize = await GetProduct(id);
            productViewModel.Supplier = productatualize.Supplier;
            productViewModel.ImagePath = productatualize.ImagePath;
            if (!ModelState.IsValid)
            {
                return View(productViewModel);
            }

            if (productViewModel.ImageUpload != null)
            {
                var imgImageName = Guid.NewGuid() + "_";
                if (!await UploadFile(productViewModel.ImageUpload, imgImageName))
                {
                    return View(productViewModel);
                }
                productatualize.ImagePath = imgImageName + productViewModel.ImageUpload.FileName;
            }
            //evita na edição a mudança de campos que vc não quer, como adicionar um novo fornecedor, por exemplo
            productatualize.Name = productViewModel.Name;
            productatualize.BarCode = productViewModel.BarCode;
            productatualize.QuantityStock = productViewModel.QuantityStock;
            productatualize.Active = productViewModel.Active;
            productatualize.PriceSales = productViewModel.PriceSales;
            productatualize.PricePurchase = productViewModel.PricePurchase;
            productatualize.Category = productViewModel.Category;

            await _productRepository.Atualizar(_mapper.Map<Product>(productatualize));
            return RedirectToAction("Index");
        }


        public async Task<IActionResult> Delete(Guid id)
        {
            var product = await GetProduct(id);

            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var product = await GetProduct(id);

            if (product == null)
            {
                return NotFound();
            }
            await _productRepository.Remover(id);
            return RedirectToAction("Index");
        }



        private async Task<ProductViewModel> GetProduct(Guid id)
        {
            var product = _mapper.Map<ProductViewModel>(await _productRepository.GetProductSupplier(id));
            product.Suppliers = _mapper.Map<IEnumerable<SupplierViewModel>>(await _supplierRepository.ObterTodos());
            return product;
        }


        //Preencher a Model 
        private async Task<ProductViewModel> FillSupplier(ProductViewModel product)
        {
            product.Suppliers = _mapper.Map<IEnumerable<SupplierViewModel>>(await _supplierRepository.ObterTodos());
            return product;
        }

        private async Task<bool> UploadFile(IFormFile file, string imgImageName)
        {
            if (file.Length <= 0) // imagem não está boa
            {
                return false;
            }

            var path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot/Images", imgImageName + file.FileName);

            if (System.IO.File.Exists(path)) // se já tiver arquivo com mesmo nome
            {
                ModelState.AddModelError(string.Empty, "There is already a file with this name!");
                return false;
            }

            using (var stream = new FileStream(path, FileMode.Create))
            {
                await file.CopyToAsync(stream);
            }

            return true;
        }
    }
}

src/Century.WebApp/Controllers/SuppliersController.cs
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Century.WebApp.Models;
using Century.Business.Interfaces;
using AutoMapper;
using Century.Business.Models;
using Microsoft.AspNetCore.Authorization;

namespace Century.WebApp.Controllers
{
    public class SuppliersController : BaseController
    {
        private readonly ISupplierRepository _supplierRepository;
        private readonly IMapper _mapper;


        public SuppliersController(ISupplierRepository supplierRepository, IMapper mapper)
        {
            _supplierRepository = supplierRepository;
            _mapper = mapper;
        }             
       [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            return View(_mapper.Map<IEnumerable<SupplierViewModel>>(await _supplierRepository
                 .ObterTodos()));
        }

        [AllowAnonymous]
        public async Task<IActionResult> Details(Guid id)
        {
            var supplierViewModel = await GetSupplierAddressPhoneEmail(id);

            if (supplierViewModel == null)
            {
                return NotFound();
            }

            return View(supplierViewModel);           
        }
        
        public IActionResult Create()
        {
            return View();
        }
             
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SupplierViewModel supplierViewModel)
        {
            if (!ModelState.IsValid)
            {
                return View(supplierViewModel);
            }

            var supplier = _mapper.Map<Supplier>(supplierViewModel);
            await _supplierRepository.Adicionar(supplier);

            return RedirectToAction("Index");
        }
      
        public async Task<IActionResult> Edit(Guid id)
        {
            var supplierViewModel = await GetSupplierProductsAddressPhoneEmail(id);
           
            if (supplierViewModel == null)
            {
                return NotFound();
            }
            return View(supplierViewModel);
        }

        // POST: Suppliers/Edit/5        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, SupplierViewModel supplierViewModel)
        {
            if (id != supplierViewModel.Id)
            {
                return NotFound();
            }

            if (!ModelState.IsValid)
            {
                return View(supplierViewModel);
            }

            var supplier = _mapper.Map<Supplier>(supplierViewModel);
            await _supplierRepository.Atualizar(supplier);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Delete(Guid id)
        {
            var supplierViewModel = await GetSupplierAddressPhoneEmail(id);
                
            if (supplierViewModel == null)
            {
                return NotFound();
            }

            return View(supplierViewModel);
        }
                
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var supplierViewModel = await GetSupplierAddressPhoneEmail(id);

            if(supplierViewModel == null)
            {
                return NotFound();
            }

            await _supplierRepository.Remover(id);

            return RedirectToAction("Index");
        }      


        private async Task<SupplierViewModel> GetSupplierAddressPhoneEmail(Guid id)
        {
            return _mapper.Map<SupplierViewModel>(await _supplierRepository
                .GetSupplierAddressPhoneEmail(id));
        }

        private async Task<SupplierViewModel> GetSupplierProductsAddressPhoneEmail(Guid id)
        {
            return _mapper.Map<SupplierViewModel>(await _supplierRepository
                .GetSupplierProductsAddressPhoneEmail(id));
        }


    }
}

src/Century.WebApp/Views/Shared/_Layout.cshtml
@System.Globalization.CultureInfo.CurrentUICulture
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Century.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Century.WebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Suppliers" asp-action="Index">Suppliers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                        </li>
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Categories" asp-action="Index">Categories</a>
                        </li>*@
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Century.WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>